### ISSUE TITLE
Schema validation failed on `ng serve`

### ISSUE THREAD

**Issue by JeffreyArt1** [chihab/dotenv-run#74]
I recently upgraded Angular to `v17.1.0` and `ng serve` is outputting this error message:

```
Error: Schema validation failed with the following errors:
  Data path "" must have required property 'main'.
```

It seems that `ng build` is not affected by this issue tho.

**To reproduce this issue:**
install a new app `ng new <app>` and add the builder `ng add @ngx-env/builder`

**Comment by Smerlyn-Javier** [comment]
I have the same issue 🫤, thanks @JeffreyArt1. ⭐️

**Comment by chihab** [comment]
I've published a new version of the builder `@ngx-env/builder@17.1.0`
`npx ng add @ngx-env/builder@latest`

**Comment by JeffreyArt1** [comment]
Still having the same issue with the new version `@ngx-env/builder@17.1.0`
```
Error: Schema validation failed with the following errors:
  Data path "" must have required property 'main'.
```

Do i have to add anything into `angular.json`?

**Comment by chihab** [comment]
What version did you have before?

**Comment by JeffreyArt1** [comment]
> What version did you have before?

`v17.0.9`

**Comment by chihab** [comment]
Fix published, could you give it another try please? 
`npx ng add @ngx-env/builder@latest`

**Comment by JeffreyArt1** [comment]
It worked! thanks
